@base_url = http://0.0.0.0:8085/v1/projects/local

GET {{base_url}}/topics
Accept: application/json

###

GET {{base_url}}/subscriptions
Accept: application/json

###

PUT {{base_url}}/topics/example1
Accept: application/json

###

PUT {{base_url}}/topics/example2
Accept: application/json

###

PUT {{base_url}}/subscriptions/example1_sub
Content-Type: application/json
Accept: application/json

{
    "topic": "projects/local/topics/example1",
    "ackDeadlineSeconds": 60,
    "enableMessageOrdering": false
}

###

PUT {{base_url}}/subscriptions/example2_sub
Content-Type: application/json
Accept: application/json

{
    "topic": "projects/local/topics/example2",
    "ackDeadlineSeconds": 60,
    "enableMessageOrdering": false
}

###

DELETE {{base_url}}/subscriptions/example1_sub
Accept: application/json

###

DELETE {{base_url}}/subscriptions/example2_sub
Accept: application/json

###

DELETE {{base_url}}/topics/example1
Accept: application/json

###

DELETE {{base_url}}/topics/example2
Accept: application/json

###
