@base_url = http://0.0.0.0:8085/v1/projects/local

# List topics

GET {{base_url}}/topics
Accept: application/json

###

# List subscriptions

GET {{base_url}}/subscriptions
Accept: application/json

###

# Create topic "example1"

PUT {{base_url}}/topics/example1
Accept: application/json

###

# Create topic "example2"

PUT {{base_url}}/topics/example2
Accept: application/json

###

# Create subscription "example1_sub" to topic "example1"

PUT {{base_url}}/subscriptions/example1_sub
Content-Type: application/json
Accept: application/json

{
    "topic": "projects/local/topics/example1",
    "ackDeadlineSeconds": 60,
    "enableMessageOrdering": false
}

###

# Create subscription "example2_sub" to topic "example2"

PUT {{base_url}}/subscriptions/example2_sub
Content-Type: application/json
Accept: application/json

{
    "topic": "projects/local/topics/example2",
    "ackDeadlineSeconds": 60,
    "enableMessageOrdering": false
}

###

# Delete subscription "example1_sub"

DELETE {{base_url}}/subscriptions/example1_sub
Accept: application/json

###

# Delete subscription "example2_sub"

DELETE {{base_url}}/subscriptions/example2_sub
Accept: application/json

###

# Delete topic "example1"

DELETE {{base_url}}/topics/example1
Accept: application/json

###

# Delete topic "example2"

DELETE {{base_url}}/topics/example2
Accept: application/json

###
